spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/casa-do-codigo
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false